include:
  - traefik/compose.yml
  - database/compose.yml
  - maildev/compose.yml
  - observability/compose.yml
  - plc/compose.yml
  # - pds/compose.yml
  - pds/compose.rsky.yml
  - relay/compose.yml
  - moderation/compose.yml
  - appview/compose.yml
  - feedgen/compose.yml
  - social/compose.yml
  - tests/compose.yml
