receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  datadog:
    endpoint: 0.0.0.0:8126

processors:
  batch:
    timeout: 10s

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 100
    sampling_thereafter: 100

service:
  pipelines:
    traces:
      receivers: [otlp, datadog]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
