-- PLC Directory Service
CREATE USER plc WITH PASSWORD 'plc';
CREATE DATABASE plc OWNER plc;
GRANT ALL PRIVILEGES ON DATABASE plc TO plc;

-- Relay Service
CREATE USER relay WITH PASSWORD 'relay';
CREATE DATABASE relay OWNER relay;
GRANT ALL PRIVILEGES ON DATABASE relay TO relay;

-- Ozone Moderation Service
CREATE USER ozone WITH PASSWORD 'ozone';
CREATE DATABASE ozone OWNER ozone;
GRANT ALL PRIVILEGES ON DATABASE ozone TO ozone;

-- Bsky Service
CREATE USER bsky WITH PASSWORD 'bsky';
CREATE DATABASE bsky OWNER bsky;
GRANT ALL PRIVILEGES ON DATABASE bsky TO bsky;
