services:
  feedgen:
    image: ghcr.io/eurosky-social/feed-generator:feedgen-latest
    volumes:
      - feedgen_data:/data
    environment:
      - FEEDGEN_PORT=3000
      - FEEDGEN_LISTENHOST=0.0.0.0
      - FEEDGEN_SQLITE_LOCATION=/data/db.sqlite
      - FEEDGEN_SUBSCRIPTION_ENDPOINT=wss://relay.${PARTITION}.${DOMAIN}
      - FEEDGEN_HOSTNAME=feedgen.${PARTITION}.${DOMAIN}
      - FEEDGEN_SUBSCRIPTION_RECONNECT_DELAY=3000
    depends_on:
      traefik-https-check:
        condition: service_healthy
      relay-post-setup:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.feedgen.rule=Host(`feedgen.${PARTITION}.${DOMAIN}`)"
      - "traefik.http.routers.feedgen.entrypoints=websecure"
      - "traefik.http.routers.feedgen.tls.certresolver=letsencrypt"
      - "traefik.http.services.feedgen.loadbalancer.server.port=3000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/.well-known/did.json || exit 1",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  feedgen-post-setup:
    image: alpine:latest
    restart: "no"
    depends_on:
      feedgen:
        condition: service_healthy
      relay-post-setup:
        condition: service_healthy
    environment:
      - PDS_HOST=pds.${PARTITION}.${DOMAIN}
      - FEEDGEN_HOST=feedgen.${PARTITION}.${DOMAIN}
    volumes:
      - ./post-setup.sh:/post-setup.sh:ro
      - feedgen_publisher_did:/shared
    command: sh -c "apk add --no-cache curl && sh /post-setup.sh"
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/ready"]
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 5s


  feedgen-https-check:
    extends:
      file: ../templates/compose.yml
      service: https-check
    depends_on:
      feedgen:
        condition: service_healthy
    environment:
      HEALTHCHECK_URL: feedgen.${PARTITION}.${DOMAIN}/.well-known/did.json

volumes:
  feedgen_data:
  feedgen_publisher_did:
