services:
  social:
    image: ghcr.io/eurosky-social/social-app:bskyweb-latest
    entrypoint: ["/usr/local/bin/social-wrapper.sh"]
    environment:
      - ATP_APPVIEW_HOST=https://bsky.${PARTITION}.${DOMAIN}
      - ATP_PUBLIC_APPVIEW_HOST=https://bsky.${PARTITION}.${DOMAIN}
      - ATP_DEFAULT_LABELER_DID=${OZONE_ADMIN_DID}
    volumes:
      - feedgen_publisher_did:/shared:ro
      - ./social-wrapper.sh:/usr/local/bin/social-wrapper.sh:ro
    depends_on:
      traefik-https-check:
        condition: service_healthy
      bsky-https-check:
        condition: service_healthy
      feedgen-post-setup:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.social.rule=Host(`social.${PARTITION}.${DOMAIN}`)"
      - "traefik.http.routers.social.entrypoints=websecure"
      - "traefik.http.routers.social.tls.certresolver=letsencrypt"
      - "traefik.http.services.social.loadbalancer.server.port=8100"
    healthcheck:
      test: ["CMD-SHELL", "pidof bskyweb || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s


  social-https-check:
    extends:
      file: ../templates/compose.yml
      service: https-check
    depends_on:
      social:
        condition: service_healthy
    environment:
      HEALTHCHECK_URL: social.${PARTITION}.${DOMAIN}

volumes:
  feedgen_publisher_did:
