services:
  social:
    build:
      context: ../social-app
      dockerfile: Dockerfile
    entrypoint: ["/usr/local/bin/social-wrapper.sh"]
    environment:
      - ATP_APPVIEW_HOST=https://bsky.${PARTITION}.${DOMAIN}
      - ATP_PUBLIC_APPVIEW_HOST=https://bsky.${PARTITION}.${DOMAIN}
    volumes:
      - feedgen_publisher_did:/shared:ro
      - ./social-wrapper.sh:/usr/local/bin/social-wrapper.sh:ro
    depends_on:
      traefik-https-check:
        condition: service_healthy
      bsky:
        condition: service_healthy
      feedgen-post-setup:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.social.rule=Host(`social.${PARTITION}.${DOMAIN}`)"
      - "traefik.http.routers.social.entrypoints=websecure"
      - "traefik.http.routers.social.tls.certresolver=letsencrypt"
      - "traefik.http.services.social.loadbalancer.server.port=8100"
    healthcheck:
      test: ["CMD-SHELL", "pidof bskyweb || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  feedgen_publisher_did:
