services:
  plc:
    image: ghcr.io/erikologic/did-method-plc:latest
    environment:
      DB_CREDS_JSON: '{"username":"plc","password":"plc","host":"postgres","port":"5432","database":"plc"}'
      DB_MIGRATE_CREDS_JSON: '{"username":"plc","password":"plc","host":"postgres","port":"5432","database":"plc"}'
      ENABLE_MIGRATIONS: "true"
      LOG_ENABLED: "true"
      LOG_LEVEL: "info"
      PORT: 3000
    depends_on:
      traefik-https-check:
        condition: service_healthy
      postgres:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plc.rule=Host(`plc.${PARTITION}.${DOMAIN}`)"
      - "traefik.http.routers.plc.entrypoints=websecure"
      - "traefik.http.routers.plc.tls.certresolver=letsencrypt"
      - "traefik.http.services.plc.loadbalancer.server.port=3000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --output-document=/dev/null http://localhost:3000/_health",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
